apiVersion: v1
kind: Service
metadata:
  name: huo-er-mu-ci-hai-xia
  labels:
    app.kubernetes.io/name: huo-er-mu-ci-hai-xia
    app.kubernetes.io/part-of: huo-er-mu-ci-hai-xia
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: huo-er-mu-ci-hai-xia
    app.kubernetes.io/part-of: huo-er-mu-ci-hai-xia
  ports:
    - name: http
      port: 80
      targetPort: 3000
