apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
  - ingress-preview.yaml
  - public-env.configmap.yaml
images:
  - name: ghcr.io/gateszhangc/hormuz-brief
    newTag: 337b2c108eb6ea143827167a0f4b3c0ef0feb1fc
