apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
  - ingress-preview.yaml
  - public-env.configmap.yaml
images:
  - name: ghcr.io/gateszhangc/hormuz-brief
    newTag: 83ab1b9e1c8ba4fac41761065f136f914ddfaf4e
