apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
  - ingress-preview.yaml
  - public-env.configmap.yaml
images:
  - name: ghcr.io/gateszhangc/hormuz-brief
    newTag: 57b8d7d60f0aa21b745efff8b0051b05d8fbaa8d
