apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/gateszhangc/quan-hong-chan
    newName: ghcr.io/gateszhangc/quan-hong-chan
    newTag: a812820bda6e49a619721e61b2787592f4939d24
