apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/gateszhangc/quan-hong-chan
    newName: ghcr.io/gateszhangc/quan-hong-chan
    newTag: ad7be0e3240dae66f2389e572e7f3f2db5a99786
