apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/gateszhangc/quan-hong-chan
    newName: ghcr.io/gateszhangc/quan-hong-chan
    newTag: 1c4c069d85aab9be5db2a4bef14de0eb13d352ed
